name = "google-ads-dashboard"
compatibility_date = "2026-09-01"
pages_build_output_dir = "./dist"

[vars]
ENVIRONMENT = "production"
GOOGLE_CLIENT_ID = "594825739440-1cmpg8el1f1h8pui26kuquo69dtf4698.apps.googleusercontent.com"
GOOGLE_ADS_CUSTOMER_ID = ""
